<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_DangNhap</name>
   <tag></tag>
   <elementGuidId>5af61731-03bd-4caa-963d-a39192aa940b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick='Account.login(this);']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Đăng nhập để bắt đầu làm việc&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f5f82d85-a2d2-46c8-85e8-28bd2fabc1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2a514ace-11d5-4e62-af64-081d5eaec7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Account.login(this);</value>
      <webElementGuid>42f6642b-e2cc-4590-9e34-89ee851c30c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng nhập để bắt đầu làm việc</value>
      <webElementGuid>46ea9e48-fcbc-44e8-afeb-4fa213252df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authform&quot;)/div[@class=&quot;form&quot;]/div[@class=&quot;row relative xo&quot;]/div[@class=&quot;submit&quot;]</value>
      <webElementGuid>5b0c808a-8ddc-4d31-96c7-c2d7b6cb4d58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick='Account.login(this);']</value>
      <webElementGuid>9c595d4c-6e0b-4d07-9e94-adc0822a74d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='authform']/div[2]/div[6]/div[2]</value>
      <webElementGuid>1f9459f3-437e-47a0-974f-7fe83c654e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quên mật khẩu?'])[1]/following::div[5]</value>
      <webElementGuid>8405fa48-9e9f-40b2-b3f3-7973b0f0af28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoặc, đăng nhập thông qua SSO'])[1]/preceding::div[1]</value>
      <webElementGuid>bc061c2e-af91-42c5-8de3-7ce285b5b3f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập bằng Google'])[1]/preceding::div[4]</value>
      <webElementGuid>793af89e-e4e8-4a5c-a3b8-494cec84799a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đăng nhập để bắt đầu làm việc']/parent::*</value>
      <webElementGuid>fbfa1266-3e46-4c3b-8a0d-3c10dfd09b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]</value>
      <webElementGuid>595d0e9e-aaf9-4a7a-bc1f-e3df12533db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Đăng nhập để bắt đầu làm việc' or . = 'Đăng nhập để bắt đầu làm việc')]</value>
      <webElementGuid>b2b4e88a-eb65-4a0e-bcd3-2fbe5f7e5dcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
