<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_itemChatBox</name>
   <tag></tag>
   <elementGuidId>fec49da3-5629-49fe-ae8c-c324826060ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='items']//div[contains(@class,'li') and contains(.,'${sTenKenh}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#msg-menu-64988</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;NN new Realtel created the channel 0&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>31a58b80-cf05-431d-a2ad-4d114c3aaaa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>li url js-channel js-channel-64988 active</value>
      <webElementGuid>3fc356eb-c6ce-4df5-98a0-ce9ba8958869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>msg-menu-64988</value>
      <webElementGuid>417ade2f-033e-4d8c-bccc-f04172e0872c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-channel</name>
      <type>Main</type>
      <value>64988</value>
      <webElementGuid>c9339c11-b257-47b3-a964-686137cd7967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>channel/64988</value>
      <webElementGuid>60733b22-f03c-4760-9b24-e57f8546b227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     NN   new Realtel created the channel  0 </value>
      <webElementGuid>2c6cde82-e6a4-440e-98f4-5821229e5858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msg-menu-64988&quot;)</value>
      <webElementGuid>61e468ff-8f6e-434d-899c-ceb4f99352c0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
