<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_MoreAction</name>
   <tag></tag>
   <elementGuidId>2b197e85-7ca5-48d7-a626-303f89f891b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='master-panel']/div/div[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_uuid84632_82994_1711541446</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;_uuid84632_82994_1711541446&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1e579b6f-0d54-46fb-9251-2a7b1ba90b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item url</value>
      <webElementGuid>f4c39dbd-6aef-4b6e-827b-00fdb504e0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_uuid84632_82994_1711541446</value>
      <webElementGuid>1c2b6893-2c76-48f0-ab40-360c82a92b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>            Tin nhắn trực tiếp   Tiếp tục       Tạo nhóm chat Nhóm chat giới hạn tối đa 100 người      Tạo kênh mới Kênh giới hạn tối đa 200 người      Tạo kênh công ty Kênh công ty tự động có tất cả các thành viên của công ty, thông báo tin nhắn sẽ tắt trừ khi được đề cập đến — BETA      Thêm danh mục mới Danh mục giúp tổ chức cuộc trò chuyện của bạn   </value>
      <webElementGuid>9b0dc2ba-7428-47ed-b61f-28282aefa907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_uuid84632_82994_1711541446&quot;)</value>
      <webElementGuid>b3289530-f981-42cf-8740-411ae47c5ff1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='master-panel']/div/div[7]</value>
      <webElementGuid>0785cdfc-af77-439e-a378-9918892d041a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thành viên'])[1]/following::div[1]</value>
      <webElementGuid>27ce598e-75d2-4c7a-b65a-933eaf728acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tin nhắn'])[1]/following::div[5]</value>
      <webElementGuid>56bc1b5d-ce9b-4679-bbee-7992047f942a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/div/div[7]</value>
      <webElementGuid>e005441b-5fb8-4efd-89f8-8f091607e999</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
